title = "PyLadies Grand Rapids"
baseURL = "https://grandrapids.pyladies.com/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "PyLadies is a group of developers worldwide who love the Python programming language."
  facebook = "https://www.facebook.com/pyladiesgrandrapids/"
  twitter = "https://twitter.com/pyladiesgr"
  instagram = ""
  youtube = ""
  github = "https://github.com/PyLadiesGR"
  slack = "https://join.slack.com/t/pyladiesgrandrapids/shared_invite/enQtODI3ODY4Mzc0OTQ4LWJhNWM0NjVmOThiNjBjYmYzMTU5NGNlMWE5MTE1N2MyN2EyMWNkNDUxZTM5ZTZjYjY0ZTI4MzhiYWM1ZWRmMDQ"
  background_color_class = "bg-dark-gray" # http://tachyons.io/docs/themes/skins/
  featured_image = "/images/calderplaza3.jpg"
  recent_posts_number = 1
